name: Run Tests Without Brisk
on: [push]
jobs:
  No-Brisk:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.0
      - run: yarn
      - run: yarn test
